version: "3.8"
services:
  flask-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_app
    ports:
      - "8080:8080"
    environment:                     
      - FLASK_DEBUG=0
      - DB_NAME=test-db
      - DB_COLLECTION_NAME=test-collection        
      - DB_CONNECTION_STRING=mongo
  mongo:
    image: mongo
 
  nginx:
    build: ./nginx
    container_name: nginx
    environment:
      - SERVER_NAME=0.0.0.0
    restart: always